sudo: required

services:
  - docker

install:
  - docker build --tag bodsch/docker-go-carbon .
  - docker run --detach --name go-carbon bodsch/docker-go-carbon

script:
  - docker ps | grep -q go-carbon

