sudo: required

services:
  - docker

env:
  global:
    - BUILD_TYPE=${BUILD_TYPE:-stable}
    - GOCARBON_VERSION=${GOCARBON_VERSION:-0.12.0}

jobs:
  include:
    - stage: build, test and push docker image
      script:
        - make build
        - make start
        - docker ps | grep -q go-carbon
        - make stop
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker push ${DOCKER_USERNAME}/docker-go-carbon:${ICINGAWEB_VERSION}
