sudo: required
services:
- docker
env:
  global:
  - BUILD_TYPE=${BUILD_TYPE:-stable}
  - GOCARBON_VERSION=${GOCARBON_VERSION:-0.14.0}
  - DOCKER_USERNAME=bodsch
  - secure: QoHoqdAAemHPKDl/v3AQNKgUEpmZjTLMYZu9d+nvicwF/ZQkb8JVokVUUC/q4cLNJjhAdblNtkkJ5gA+EKgC8oZr56kbmlSjqUgvXNak9NC1qbjUblyDQQdFJEthxwbSU/S3Hc3Bn1BVPxJi5ggMw++ujwHDVeaDkBa/yhKzIBNufdVKKnwhzZ+ylSXKyVMqMlYstC9nSyRNs2OKhxqL5I7n2cX9/UIDcQeY5tl4rTnQfaj7t46l46izhJTNFMmWI9I9/XWJMpo2oYnoF+ksxbcvqAPPTP4+My70f0Rt6c5K4vfkswkNUbNa2tnRkIAwcMeHtgy3Kl/Ls+N5LIEACGJliv3QQcn/dObL6iGFy/hlR/zJ8bYNJ/JWvl8IH+ZPd4X9WM0inn4oACAEx2dpKgldVzfr49HEFLWyUv8JEWObg/fW+vJMr1XUByo/e2dxOXBM6ZGMaNnVj04Nsl7imU8ZhMttk0p7VE+0EUtALKWFITYHsy0y40u4rL0/84dh+49di6L07QE8xwVcqE+dwnVYqM/ACdzXyAq+9fO+3NeZgbzIbfrWcr4BzPctduzatZhuszaZfcvVo8wsdj9srwOIKU9slZL/BF+2whWa1RieIbIMwS28K/WbhIIOLgqMrOMd4fN2DhFPtpOJTeUyHuCyPvXJN5/0MmEdB/8awD8=
jobs:
  include:
  - stage: build
    script:
    - make
  - stage: build and test
    script:
    - make
    - make start
    - make test
    - make stop
  - stage: build and push docker image
    script:
    - make
    - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
    - docker tag  ${USER}/go-carbon:latest ${DOCKER_USERNAME}/docker-go-carbon:latest
    - docker push ${DOCKER_USERNAME}/docker-go-carbon:latest
    - docker tag  ${DOCKER_USERNAME}/docker-go-carbon:latest ${DOCKER_USERNAME}/docker-go-carbon:${GOCARBON_VERSION}
    - docker push ${DOCKER_USERNAME}/docker-go-carbon:${GOCARBON_VERSION}
    - docker logout
