sudo: required
services:
- docker
env:
  global:
  - BUILD_TYPE=${BUILD_TYPE:-stable}
  - GOCARBON_VERSION=${GOCARBON_VERSION:-0.14.0}
  - DOCKER_USERNAME=bodsch
  - secure: c5TftmG08cB3zQM5/Ktv6vS1JqrKQAvhW0Ampxo3Yphmm1SEzVglcaeyHdK0LRNSu0YiTreDSpIvbioHwinUIvSD0Zs8gQ+Gkq9oROjbu/tZZ56eX1UOVMaudDpTz693NyykT9heRBVNfGseV+eia3n3rz7JB0oNrgwTG3jpTpQtsQPS9oGuYNz8cwfu25BuXOVhfzZue9sj9R+YxAutcGorA+5sX6xEX5zMoPIQlljqYPtzIVeoF+c+eQx6dhyToqqdfLWp/XZctKBdGR73suecmiRpAKRUfPc7OreIpgBmoZxHW5G4KL3A2lRCivpwgDFSF2bQj7CzTnhVsAva9YY04TzWVS13I+wzi/gdjlk+bFWJC9ONm4nUzWSAnZMepxxdOcwIzhEnc/7diJb3Ni7hsVcg42tXVRXvwGDHn9SRPqYFe3b0VZ8dfSNV7+aNFp2PU3vph2DIK9Fl8DyuyF//3Y+6zHVlT6jpemtRTy3LECWB8T7rsZVDT77nvySqkk3/p2n7jEDqNnJiI4wjeqPER77ygs3H42QBEp8bJw6dz4Jw1QBMgER1y5LIh+3Q89cPZiGijKzt4FD/MxpduHU74GHJCbkfyJMqjkBj77ataqoxpSp9IO/qyNSEXskIF4+jniXkTHdgNGcerPiW+Kqf/jW0pw0LVPjhHt2MU80=

jobs:
  include:
  - stage: build
    script:
      - make

  - stage: build and test
    script:
      - make
      - make start
      - make test
      - make stop

  - stage: build and push docker image
    script:
      - make
      - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
      #
      - docker tag  ${USER}/go-carbon:latest ${DOCKER_USERNAME}/docker-go-carbon:latest
      - docker push ${DOCKER_USERNAME}/docker-go-carbon:latest
      #
      - docker tag  ${DOCKER_USERNAME}/docker-go-carbon:latest ${DOCKER_USERNAME}/docker-go-carbon:${GOCARBON_VERSION}
      - docker push ${DOCKER_USERNAME}/docker-go-carbon:${GOCARBON_VERSION}
      - docker logout

