[template]
src = "carbon.conf.tpl"
dest = "/etc/go-carbon/carbon.conf"
keys = [
    "/go-carbon/max-cpu",
    "/go-carbon/common/user",
    "/go-carbon/common/graph-prefix",
    "/go-carbon/common/metric-endpoint",
    "/go-carbon/common/max-cpu",
    "/go-carbon/common/metric-interval",
    "/go-carbon/whisper/enabled",
    "/go-carbon/whisper/data-dir",
    "/go-carbon/whisper/schemas-file",
    "/go-carbon/whisper/aggregation-file",
    "/go-carbon/whisper/workers",
    "/go-carbon/whisper/max-updates-per-second",
    "/go-carbon/whisper/sparse-create",
    "/go-carbon/cache/max-size",
    "/go-carbon/cache/write-strategy",
    "/go-carbon/udp/enabled",
    "/go-carbon/udp/listen",
    "/go-carbon/udp/log-incomplete",
    "/go-carbon/udp/buffer-size",
    "/go-carbon/tcp/enabled",
    "/go-carbon/tcp/listen",
    "/go-carbon/tcp/buffer-size",
    "/go-carbon/pickle/enabled",
    "/go-carbon/pickle/listen",
    "/go-carbon/pickle/max-message-size",
    "/go-carbon/pickle/buffer-size",
    "/go-carbon/carbonlink/enabled",
    "/go-carbon/carbonlink/listen",
    "/go-carbon/carbonlink/read-timeout",
    "/go-carbon/carbonlink/query-timeout",
    "/go-carbon/grpc/enabled",
    "/go-carbon/grpc/listen",
    "/go-carbon/carbonserver/enabled",
    "/go-carbon/carbonserver/listen",
    "/go-carbon/carbonserver/query-cache-enabled",
    "/go-carbon/carbonserver/query-cache-size-mb",
    "/go-carbon/carbonserver/find-cache-enabled",
    "/go-carbon/carbonserver/buckets",
    "/go-carbon/carbonserver/max-globs",
    "/go-carbon/carbonserver/fail-on-max-globs",
    "/go-carbon/carbonserver/metrics-as-counters",
    "/go-carbon/carbonserver/trigram-index",
    "/go-carbon/carbonserver/graphite-web-10-strict-mode",
    "/go-carbon/carbonserver/internal-stats-dir",
    "/go-carbon/carbonserver/read-timeout",
    "/go-carbon/carbonserver/idle-timeout",
    "/go-carbon/carbonserver/write-timeout",
    "/go-carbon/carbonserver/scan-frequency",
    "/go-carbon/dump/enabled",
    "/go-carbon/dump/path",
    "/go-carbon/dump/restore-per-second",
    "/go-carbon/pprof/enabled",
    "/go-carbon/pprof/listen",
    "/go-carbon/logging/logger",
    "/go-carbon/logging/file",
    "/go-carbon/logging/level",
    "/go-carbon/logging/encoding",
    "/go-carbon/logging/encoding-time",
    "/go-carbon/logging/encoding-duration",
]
check_cmd = "go-carbon -check-config -config {{ .src }}"
